### ISSUE TITLE
Another Nexon game

### ISSUE THREAD

**Issue by RustyUncle** [JakobKlocker/NexonGameSecurity-bypass#4]
Hello, I tried another Nexon game but it didn't work. Please can you explain step by step what exactly do I do?

**Comment by JakobKlocker** [comment]
They patched the method of blocking ZwMapViewOfSection in the recent NGS update. You have to feed Blackcipher a copy of Blackcipher when it's comparing the .tmp file. When doing so you have to change memory in Blackcipher, therefore you'll stand before a new problem which is bypassing the integrity checks of Blackcipher. Since it's more effort & it needs updating(addresses change, AoB won't work for the virtualized code) I won't bother updating it publicly for new updates. You can take this bypass as a good base tho, it bypasses a lot of checks already.
